- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host

- name: Download mongodb-compass_1.12.1_amd64
  get_url: 
    url="https://downloads.mongodb.com/compass/mongodb-compass_1.12.1_amd64.deb"
    dest="/home/{{ username_on_the_host.stdout }}/Downloads/mongodb-compass_1.12.1_amd64.deb"

- name: Install mongodb-compass_1.12.1_amd64
  apt: deb="/home/{{ username_on_the_host.stdout }}/Downloads/mongodb-compass_1.12.1_amd64.deb"
  sudo: true
